#!/usr/bin/env node
/*
 * Regenerates assets/logo-mark-embed.js from assets/logo-mark.png.
 *
 * The app loads the default logo from this embedded data: URI instead of
 * fetching the PNG file directly. Loading a local file:// image onto the
 * canvas taints it (blocks toDataURL/toBlob — i.e. every download and the
 * batch pipeline) even though it looks fine in a screenshot. A data: URI
 * never taints the canvas, regardless of whether the page is opened as a
 * local file, over http://, or hosted as an Artifact.
 *
 * Run this whenever assets/logo-mark.png changes.
 */
const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const pngPath = path.join(ROOT, "assets", "logo-mark.png");
const outPath = path.join(ROOT, "assets", "logo-mark-embed.js");

const base64 = fs.readFileSync(pngPath).toString("base64");
const js = `// Auto-generated by scripts/embed-logo.js from assets/logo-mark.png — do not edit by hand.
window.DEFAULT_LOGO_DATA_URL = "data:image/png;base64,${base64}";
`;
fs.writeFileSync(outPath, js);
console.log(`Wrote ${outPath} (${(js.length / 1024).toFixed(0)} KB)`);
